spring:
  application:
    name: download-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${SERVER_PORT}
  shutdown: graceful
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

sds:
  rate-limit:
    requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:10}
  management-service:
    base-url: ${MANAGEMENT_SERVICE_BASE_URL}
  keycloak:
    token-url: ${KEYCLOAK_TOKEN_URL}
    client-id: ${KEYCLOAK_CLIENT_ID}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
  kafka:
    topics:
      download-events: document-download-event

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  structured:
    format:
      console: logstash
