global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: management-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['management-service:8131']

  - job_name: download-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['download-service:8030']
